### ISSUE TITLE
Issues 

### ISSUE THREAD

**Issue by Balaji-1712** [HusseinJammal/Liquid-Neural-Networks-in-Stock-Market-Prediction#4]
ERROR
Network Error
AxiosError: Network Error
    at XMLHttpRequest.handleError (http://localhost:3000/static/js/bundle.js:48515:14)
    at Axios.request (http://localhost:3000/static/js/bundle.js:48967:41)

can u help me to resolve this issues....?

**Comment by HusseinJammal** [comment]
Hello @Balaji-1712 
Please provide a video recording once you enter the parameters (dates, stock name, etc...)
So that I can get a clear understanding of the issue.

Thank you!

**Comment by Balaji-1712** [comment]
Hi sir @HusseinJammal 




can u help me to resolve this issues....?
https://drive.google.com/file/d/18T9wj9Ai6e3tsVUEIBfPPb2qN8bCzH5x/view?usp=sharing
